version: "3.7"

services:
  qg-person-mock-server:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3004"]
    ports:
      - 31004:3004
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3004/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - ./mockoon-mocks.json:/data:ro
